# Generated by Django 4.0.5 on 2022-06-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_shop', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
